### ISSUE TITLE
Prevent Slideshows from building unless recently updated

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#129]
Please update the slideshow build script to **only** generate slides for a language if:
1. Output directory doesn't exist (hence it's never run) or
2. Language was updated in the past week (to be safe)

This should cut down on the number of languages that are generated each time the site is built.

**Comment by codemis** [comment]
In regards to number 2: _Language was updated in the past week (to be safe)_,  in order to get the last update, we need to pull the language data from the API.  Pulling this data is the main reason it takes so long to build the site.  Instead,  I wrote the code to generate the slides only if:
1. The output directory does not exist.
2. The output directory was created or modified more than a week ago.

Will this solve the issue, or would you prefer to pull the language data from the API?

**Comment by jag3773** [comment]
:+1:
