### ISSUE TITLE
Add ODT and DOCX exports to OBS Stories List

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#80]

**Comment by codemis** [comment]
I noticed several languages do not have those files.  So people will see the link, but will get a 404 error when visiting it.  I can use Javascript to check the file, but I am afraid that will eat up load time in the browser since I will need to ping each file and check for a 404.

Can we add a resources array to the [feed response](https://api.unfoldingword.org/obs/txt/1/obs-catalog.json) from the API that tells us what is available?  It can look something like this:

```
"resources": [
        {
          "size": "small"
         "type": "slideshow",
          "location": "https://api.unfoldingword.org/obs/txt/1/am/slides/360px/01/"
        },
        {
          "size": "large",
          "type": "slideshow",
          "location": "https://api.unfoldingword.org/obs/txt/1/am/slides/2160px/01/"
        },
        {
          "size": "",
          "type": "pdf",
          "location": "https://api.unfoldingword.org/obs/txt/1/am/obs-am-v4_1.pdf"
        },
        {
         "size": "",
          "type": "odt",
          "location": "https://api.unfoldingword.org/obs/txt/1/am/obs-am-v4_1.odt"
        },

        {
         "size": "",
          "type": "docx",
          "location": "https://api.unfoldingword.org/obs/txt/1/am/obs-am-v4_1.docx"
        }
      ]
```

**Comment by codemis** [comment]
Ok,  I added them.  You can check it out at the [test site](http://test.unfoldingword.org/stories).

**Comment by codemis** [comment]
Waiting for the ODT & DOCX files to be added to the catalog file.

**Comment by codemis** [comment]
@jag3773 Can you point me to where I can find the ODT & DOCX files on the CDN?  Thanks.

**Comment by jag3773** [comment]
@codemis I don't think they are there yet.
